### ISSUE TITLE
Change the way parameters are passed to Service Providers

### ISSUE THREAD

**Issue by mdecaffmeyer** [silexphp/Pimple#158]
The suggestion can easily be demonstrated by a straightforward example. Take the MongoDB-ODM Silex provider:
https://github.com/romainneutron/MongoDB-ODM-Silex-Provider#usage

You can see in the Usage example that all the config keys passed to the ServiceProvider are preceeded by "doctrine.odm.mongodb." to avoid collision, as the config parameters are registered in the container.
Wouldn't it then be easier to add a third parameter optionally to Pimple\Container's register method that allows to specify a prefix?

Most importantly, I have also been wondering why the config values are registered in the container at all, instead of just passing them to that specific ServiceProvider, as most of the times the config values for one ServiceProvider aren't (and should not) be used by another ServiceProvider? Why not pass the config parameters to the ServiceProvider's register() method instead of adding these parameters in the container?
(And if for some reason, some of the config parameters do need to be shared through the container, the ServiceProvider could do that itself.) That way, the ServiceProvider's config parameters aren't globally accessible from the container (which shouldn't), and of course the config parameters shouldn't even be prefixed in this case.
Instead of
```
$this->container->register($serviceProvider, $config);
```
you would just do
```
$serviceProvider->register($this->container, $config);
```
$config is now local to the ServiceProvider in question

**Comment by mdecaffmeyer** [comment]
Sorry for re-opening, I would like to discuss this again.

Currently, parameters passed to the service provider are added globally in the container, that means that usually we prefix the service provider's parameters by the service key:

```php
$container->register(new FooServiceProvider('fooService'), // fooService is the key of the service
[
    'fooService.option' => 'value',
    'fooService.db' => 'mysqlDbService',
]);
```
A better naming for keys could be the class' name as we see in other containers' documentation:

```php
$container->register(new FooServiceProvider(FooInterface::class), [
    FooInterface::class.'.option' => 'value',
    FooInterface::class.DbInterface::class => MySqlAdapter::class,
]);
```

```FooInterface::class.'.option'``` or ```'Application\Foo\FooInterface.option'``` starts to look ugly and there could be definitely a better way to pass parameters to service providers:

```php
$serviceProvider = new FooServiceProvider();
$serviceProvider->register($container, [
    'option' => $value,
    DbInterface::class => MySqlAdapter::class,
]);
```

We could pass the service provider's parameters to the ```register()``` method just as above. Unfortunately right now the ```register()``` defined in ```ServiceProviderInterface``` is the following:
```php
public function register(Container $pimple);
```

This forces to put the parameters inside the container.

The main argument against that according to @GromNaN is that it doesn't allow to override the configuration based on the environment after the service provider has been registered. However, the right parameters based on environment should be given based to the service provider straight away, or you just register the service provider again with the right parameters.

**Comment by henrikbjorn** [comment]
Well in my case my "parameters" are located in a json file, which is essentially the configuration of my application. This means i have a unified place with my configuration, and a place (my application class) why i just register service providers.

This creates seperation and is easier for multiple developers to manage. This would not be possible using the pattern described here.

**Comment by mdecaffmeyer** [comment]
@henrikbjorn I have exactly the same structure, except that I store configuration in a php configuration file, it would look something like:
```php
// services.config.php
<?php
return [
    \PDO::class => [ // service name
        'serviceProvider' => App\Pdo\Provider\Pimple\PdoServiceProvider:class,
        'parameters' => [
            'dsn' => 'sqlite:db.sqlite',
        ],
    ],
    // etcetera
];
```

And I don't see why the pattern I suggest is not possible for that (your) case, as you just loop through the service providers inside your configuration file, and you could do:
```php
$provider = new $serviceProvider($serviceName)
$provider->register($this->container, $serviceParameters);
```

Now you might wonder why I bring this up if I use a config file just like you do. Well somewhere in your service providers you should retrieve its parameters like I showed in previous comment. In the php snippet above, "dsn" will be accessed by key '\PDO.dsn'. You end up with strange keys in your container. In addition to that, service provider's parameters have no reason to be stored globally in the container anyway.

**Comment by mdecaffmeyer** [comment]
@henrikbjorn I was thinking about your config file, I guess it doesn't look like mine and you just override the parameters like:
```
"fooService.param1" : "value1",
"fooService.param2" : "value2",
"barService.param1" : "value1",
```
If so, I need to think about that. I want to have a look at how other containers allow to override parameters without redefining the Service Provider.
