### ISSUE TITLE
micro-optimization offsetGet($id)

### ISSUE THREAD

**Issue by GDmac** [silexphp/Pimple#166]
I was going to suggest in offsetGet to skip the is_object() check for a micro-optimization. 
(Xdebug profiler showed enough speed-gain, so that pimple ended up below
Composer\Autoload\ClassLoader->findFileWithExtension)

```php
// $isFactory = is_object($this->values[$id]) && method_exists($this->values[$id], '__invoke');
   $isFactory = method_exists($this->values[$id], '__invoke');
```

However in version 2 i see a whole range of new checks, have you speed tested these?

**Comment by Brahy** [comment]
The method_exists function trigger all registered autoloader if the first parameter is a string.
Thats would be bad for the performance. Sorry for my english.
