### ISSUE TITLE
isset() a service is ambiguous

### ISSUE THREAD

**Issue by raphahardt** [silexphp/Pimple#167]
Hi,

After a long time using `Pimple`, I found a little issue (what I think that is a issue).
I'm going to show a piece of code that will explain better than words:

``` php
$container = new Pimple\Container();
$container['foo'] = 'something';
$container['bar'] = null;

$array = array();
$array['foo'] = 'something';
$array['bar'] = null;

$arrayObj = new \ArrayObject();
$arrayObj['foo'] = 'something';
$arrayObj['bar'] = null;

var_dump(
    isset($array['foo']),        // TRUE
    isset($array['bar']),        // FALSE
    isset($array['unknown']),    // FALSE
    isset($arrayObj['foo']),     // TRUE
    isset($arrayObj['bar']),     // FALSE
    isset($arrayObj['unknown']), // FALSE
    isset($container['foo']),    // TRUE
    isset($container['bar']),    // TRUE - should not be FALSE?
    isset($container['unknown']) // FALSE
);
```

IMO if a parameter is value of `NULL`, then `isset()` should return `FALSE`, as behavior of an array.

The main use case: if I do not want set a `$c['logger']`, i could put value of `$c['logger'] = null` in a config file for after changing, but a code like this for testing of presence of a logger will crash:

``` php
$obj = SomeLoggerAwareObject();
if (isset($c['logger']) {
    $obj->setLogger($c['logger']); // Fatal error: expected a Logger instance, null given
}
```

Instead I have to do like this:

``` php
if (isset($c['logger'] && $c['logger'] !== null) { // ...
```

(sorry my bad english)

**Comment by mdecaffmeyer** [comment]
@raphahardt even though I had the same issue, checking with !empty() is ok for me. As you mentioned, this will execute the service as well, but when I check if a service has been disabled or not (as in your use case), I would execute it anyway right after that if enabled. Typically.:
```
if (!empty($container['logger'])) {
   // do something with $container['logger']
}
```
Could you show an example where you want to check for a disabled service and if not disabled, not willing to use it straight away?

**Comment by Dragonrun1** [comment]
The problem I see is  that offsetExists() and offsetGet() are both checking the value and not the key. they should be using ``` if(array_key_exists($id, $this->keys)) { ....``` Not doing so means it's not really possible to check for defined parameters or services. When I look at the code in Container PHPStorm lights up with a lot of red because of this and a couple other things. Think I have a little time so I'll look at doing a pull request to fix things up.

**Comment by stof** [comment]
@Dragonrun1 I don't understand your comment

**Comment by Dragonrun1** [comment]
Let's just blame my last post on writing it at 2am with no sleep I'll try to use some real code this time to explain things better.
```php
<?php
$errorReporting = error_reporting(E_ALL);
ini_set('display_errors', 1);
$keys = ['first' => true, 'second' => false, 'third' => null];
$ids = ['first', 'second', 'third', 'forth'];
print 'Using isset (No structure control)' . PHP_EOL;
foreach ($ids as $id) {
    if (isset($keys[$id])) {
        print $id . ' = Yes' . PHP_EOL;
    } else {
        print $id . ' = No' . PHP_EOL;
    }
}
print PHP_EOL . 'Using array_key_exists (Structure control only)' . PHP_EOL;
foreach ($ids as $id) {
    if (array_key_exists($id, $keys)) {
        print $id . ' = Yes' . PHP_EOL;
    } else {
        print $id . ' = No' . PHP_EOL;
    }
}
print PHP_EOL . 'Using === test (Type safety checking)' . PHP_EOL;
foreach ($ids as $id) {
    if (true === $keys[$id]) {
        print $id . ' = Yes' . PHP_EOL;
    } else {
        print $id . ' = No' . PHP_EOL;
    }
}
print PHP_EOL . 'Using array_key_exists with === test (Structurally and type safety checking)' . PHP_EOL;
foreach ($ids as $id) {
    if (array_key_exists($id, $keys) && true === $keys[$id]) {
        print $id . ' = Yes' . PHP_EOL;
    } else {
        print $id . ' = No' . PHP_EOL;
    }
}
```
Output with php 5.5.x/7.0.x:
```sh
Using isset (No structure control)
first = Yes
second = Yes
third = No
forth = No

Using array_key_exists (Structure control only)
first = Yes
second = Yes
third = Yes
forth = No

Using === test (Type safety checking)
first = Yes
second = No
third = No
PHP Notice:  Undefined index: forth in test.php on line 24

Notice: Undefined index: forth in test.php on line 24
forth = No

Using array_key_exists with === test (Structurally and type safety checking)
first = Yes
second = No
third = No
forth = No
```
Now the code from Container()
```php
    public function offsetGet($id)
    {
        if (!isset($this->keys[$id])) {
            throw new \InvalidArgumentException(sprintf('Identifier "%s" is not defined.', $id));
        }
```
It's not testing what you think it is. The code makes assumes that are easy to break.
```php
class MyContainer extends Container {
    public $keys;
    public function __construct( array $keys, array $values = array()) {
        parent::__construct($values);
        $this->keys = $keys;
}
$container = new MyContainer(['first' => true, 'second' => false, 'third' => null], []);
```
That's just one very simple example which would be easy to catch but notice the ```public $keys;``` how many more interesting ways could that end up breaking? Using ```isset()``` by itself on arrays sooner or later comes back to bite you.

Hopefully the above is a little clearer if a bit to long ;-)

**Comment by fabpot** [comment]
Closing this issue as Pimple is now closed for changes and will go into freeze mode.
