### ISSUE TITLE
Pimple factory not working properly with 2 parameters

### ISSUE THREAD

**Issue by devsdmf** [silexphp/Pimple#175]
I have this code that I register a factory for monolog in my application, but the parameter `$options` are not working, have any restriction to use more than one parameter in a factory function inside a Pimple container ?
```php
$app['monolog.factory'] = $app->factory(function ($name, array $options) use ($app) {
    $logger = new Logger($name);

    // My factory code
    
    return $logger;
});

# Compiling loggers
foreach ($config['monolog'] as $channel => $options)
{
    $app['monolog.' . $channel] = $app['monolog.factory']($channel,$options);
}
```
Follow the error message:
```
Argument 2 passed to Application\Bootstrap::Application\{closure}() must be of the type array, none given
```
I am using Silex 2.0 as app framework

**Comment by Kilte** [comment]
`factory()` defines a service, and it returns an instance, not function. Use `protect()` instead.

**Comment by devsdmf** [comment]
Oh, ok, thanks!
