### ISSUE TITLE
PHP7 support

### ISSUE THREAD

**Issue by jbboehr** [silexphp/Pimple#184]
Currently, the pure PHP implementation is passing tests on PHP7. The extension, however, requires quite a lot of work to be compatible. I've been working on it in a branch [here](https://github.com/jbboehr/Pimple/tree/php7). It's currently not compatible with PHP5. I have also been working on that, however the amount of shared code is relatively low compared to some other extensions I've worked on.

The last remaining issue is a leak in 009.phpt, however, removing the `use` there is no leak so I'm not sure it's really an issue:

```
[Thu Aug  6 14:22:04 2015]  Script:  'ext/pimple/tests/009.php'
Zend/zend_closures.c(336) :  Freeing 0x2AD910E60B40 (288 bytes), script=ext/pimple/tests/009.php
```

**Comment by jbboehr** [comment]
One thing I should note is that I just couldn't get the `get_closure` object handler working on PHP7, so I switched back to using __invoke in this branch.

**Comment by stof** [comment]
@jpauli announced a few days ago on twitter that he is working on it already

**Comment by jbboehr** [comment]
Great. If @jpauli wants to scavenge from my code, it's working on PHP7.

**Comment by onlyjob** [comment]
Ironically _Pimple_ is a dependency of [php7cc](https://github.com/sstalle/php7cc) - PHP7 compatibility checker.
[Debian](http://debian.org) is going to drop PHP-5 soon so PHP-7 compatibility is important...

**Comment by stof** [comment]
PHP 7 is perfectly supported when using the userland implementation of Pimple.

**Comment by fabpot** [comment]
Closing as the C ext has been deprecated now. The PHP code works on all supported PHP versions, including PHP 7.
