### ISSUE TITLE
No InvalidArgumentException when extending protected parameter

### ISSUE THREAD

**Issue by JakeFr** [silexphp/Pimple#190]
Hello.
When you extend a parameter, the container throws an `\InvalidArgumentException`.
But when you extend a protected closure, there are no exception and the behavior of the function is weird and difficult to debug.
`protect()` stores closure as parameter, so `extend()` should throw exception too.
Is that correct ?

**Comment by stof** [comment]
hmm, this makes sense

**Comment by JakeFr** [comment]
I can submit a PR for the php code of Pimple.
Easiest solution is to add the condition `|| isset($this->protected[$this->values[$id]])` to https://github.com/silexphp/Pimple/blob/master/src/Pimple/Container.php#L232
Or add another `if` block before or after with a more relevant wording. Thanks to suggestion.
And add a test case.
But I am not able to modify the extension part of pimple, need expert
