### ISSUE TITLE
"PimpleAwareTrait"

### ISSUE THREAD

**Issue by davidsteinsland** [silexphp/Pimple#191]
I am using Pimple as a basis for my `Application` class, and to simplify the DI process, I thought that I would override `offsetGet` with something like:

```php
$this[$offset] = $this->extend($offset, function ($obj, $app) {
    if ($obj instanceof ApplicationAwareTrait) {
        $obj->setApplication($this);
    }
    return $obj;
});
$obj = parent::offsetGet($offset);
```

Any thoughts about this? I am sure that I'm not the only one wanting to do this, but I'd like to get input from you whether this is a good approach or not.

**Comment by jvasseur** [comment]
You can't use instanceof to check if an object use a trait.

**Comment by davidsteinsland** [comment]
Yeah, that's correct, but for the sake of argument let's assume that it's an interface.

Pimple is not a dependency injector, but has anyone tried using it for such?

**Comment by stof** [comment]
Injecting the container into objects is a bad practice. So simplifying this case looks wrong to me.

Btw, we had such feature in Symfony in the past (before the 2.0-beta release). But we removed the interface-based injection as it was causing too much issues (what if you have multiple instance of Pimple around and want to control which one is injected)

**Comment by davidsteinsland** [comment]
@stof thanks for the reply. Just the kind of answer I was looking for (regarding symfony). 
What is the today's practice then? Having dependencies "injected" into the constructors? 

I've seen the dependency component in symfony, but isn't that a big elephant in contrast to pimple?

**Comment by stof** [comment]
@davidsteinsland we can still inject through setter in Symfony. What was removed form Symfony was the automatic injection of some dependencies based on the fact it implements some interface, because it caused issues more often than it proved actually useful. And this is exactly what you are trying to add into Pimple here

**Comment by davidsteinsland** [comment]
So what would you recommend, when keeping it as simple as possible?

**Comment by stof** [comment]
my recommendation would be to inject your real dependencies into the object, not Pimple itself. And for the few cases where the Pimple instance is really your dependency, you can do it explicitly in your service definition (it should not happen too often)

**Comment by davidsteinsland** [comment]
thanks. so you propose something as simple as:
```php
$app['service'] = function ($app) {
    $service = new Acme\Service($app['dependecy']);
    $service->setFooBar($app['foo.bar']);
    return $service;
};
```
? 

Sounds reasonable.

**Comment by stof** [comment]
this is the way you should use it yes. Your classes should not depend on Pimple itself most of the time (it will also make your code more readable and easier to test btw)
