### ISSUE TITLE
Weird bug in C extension

### ISSUE THREAD

**Issue by fedeisas** [silexphp/Pimple#196]
Hi there! I just spent 2 hours fighting a bug, but I'm not sure on the steps to replicate it.

My dev environment config for php-fpm is set to dynamic with 2 servers.

I added a new service to our Container, and it started to failed 50% of the requests. One worked, the next didn't, the next worked, etc.

I started debugging the container and I realized the new service on the container wasn't getting injected on this failed requests. My co-workers could run the code without any problem.

I tried restarting nginx and php5-fpm with no luck.

After a while I remembered 6 months ago I installed the C extension for pimple. When I disabled it, it started working again.

If there's any extra info I can give to this bug report, let me know. Thanks!

**Comment by mcaskill** [comment]
I've recently been suffering from the same issue with PHP 5.6 (without FPM). Using Homebrew to provide PHP and Pimple extension. Issue started two weeks ago, suddenly 50% of requests would fail, then it'd be 75%, now it's sort 99%. Disabling the extension fixes the issue. Apache would log a segmentation fault every time the request would fail.

**Comment by petrkotek** [comment]
Which version do you guys use? v3.0.2 has some fix for C extension segfault, see `CHANGELOG`: https://github.com/silexphp/Pimple/blob/v3.0.2/CHANGELOG#L9

**Comment by fabpot** [comment]
Closing as the C extension has been deprecated now.
