### ISSUE TITLE
Child or Prefixed, Merged Containers

### ISSUE THREAD

**Issue by ragboyjr** [silexphp/Pimple#200]
## Feature

I'd like to propose the ability to create a container with a key prefix so that all of the definitions on this container will be prefixed. This would very similar to cache key prefix. This also however, would then need the ability to merge/join containers together.

```php
<?php

use Pimple\Container;

$app = new Container();
$app['key1'] = function() {};
$sub = new Container('app.prefix.');
$sub['key1'] = function() {};

$app = $app->join($sub); // join/merge not sure which method name I prefer
// this app now contains the keys: `key1` and `app.prefix.key1`
```

This would help a lot, but another feature similar to this that would be even nicer would be Child/View containers. In this scenario, a parent container can create a prefixed child container, when you look up a service in this child container, it will look in its own definitions first, if not found, then delegates responsibility to the parent container.

```php
<?php

use Pimple\Container;

$app = new Container();
$app['app.key'] = function() {};
$child = $app->child('app.some_prefix.');
$child['key']; // this would resolve to `app.key` because the child container doesn't have this definition
```

## Implementation

Now, you could skin this cat a few different ways. The straight forward solution would to just add these methods into the `Pimple\Container`, there'd be no BC breaks.

Another implementation (the one I'd really prefer), is if you created a `ContainerInterface` for Pimple. In this event, you could simply create decorators for each of these features. You could create a Prefix decorator that would take an app and apply a prefix to it. On set, it applies the prefix, on fetch or has, it will apply the prefix, if no match, then it will take out prefix and try again. In addition, using an interface would open up to a bunch of different possibilities of cool things you could do without breaking or even adding any API's.

example:

```php

$app = new Pimple\Container();
$app['key'] = function() {};
$prefixed = new Pimple\PrefixedContainer($app, 'app.prefix.');
$prefixed['key1'] = function() {};

// $app now has two keys: `key` and `app.prefix.key`
```

## Why

In some of my larger applications that use pimple, I create a service provider per module. Then I create one service provider for my entire application that will just register each of the modules service provider. And in some cases, I might have submodules that are big enough to warrant their own Service providers, and so I'll create like a hierarchy of service providers to help keep everything modularized and maintainable. Here's a small example.

```
src/ModuleA/ModuleAServiceProvider.php
src/ModuleB/ModuleBServiceProvider.php
src/ModuleB/ModuleC/ModuleCServiceProvider.php
src/AppServiceProvider.php
```

and then `AppServiceProvider` would look like:

```php
<?php

public function register(Container $app) {
    $app->register(new ModuleA\ModuleAServiceProvider());
    $app->register(new ModuleB\ModuleBServiceProvider());
   // module c was registered in side of module b
}
```

Anyways, when you have a lot of service providers, you tend to namespace your keys for the container. So in module C, some of my keys would look like

```
myapp.module_b.module_c.some_provided_service
```

As you can see, these can get very long especially, if your namespace depth is large for some of these names. Having type out or copy and paste can be buggy at times. Hence, where being able to define your services in a prefixed container would help a lot with this.

## Conclusion

I don't know if this feature is too specific to my needs or not, so that's why I'm posting it in here to get a feel for how other developers use pimple. I'm also more than willing to do the PR for this, but I didn't want to do the work if this wasn't something the community would agree on.

**Comment by ragboyjr** [comment]
hello? anyone there?

**Comment by stof** [comment]
IMO, this is outside the scope of Pimple itself

**Comment by GromNaN** [comment]
An alternative is to set the prefix as an argument of the ServiceProvider.
That's how the [`PredisServiceProvider`](https://github.com/nrk/PredisServiceProvider/blob/master/src/ClientServiceProvider.php#L32) can be registered several times with a different service prefix.

**Comment by ragboyjr** [comment]
@GromNan I've done that before where you create a variable for the prefix, but because php closures don't automatically include outside vars, you have to constantly write `use`.

**Comment by ragboyjr** [comment]
I did some more thinking about this, and my decorator implementation actually wouldn't work because of the app's injection into the register function. If you decorated the container, you can define service no problem; however, the container that's passed into the function would still be the default container where the prefixes won't apply.

So I guess:

```php
$p = 'app.prefix.'

$app[$p.'service'] = function($app) use ($p) {
    return new Service($app[$p.'other_service']);
};
```

will have to be fine for now.

We can close this...
