### ISSUE TITLE
Service extension does not correctly detect PHP callables as closures

### ISSUE THREAD

**Issue by curry684** [silexphp/Pimple#201]
Assume the following SCCEE:

``` php
class MySilex extends \Silex\Application
{
    public function __construct()
    {
        parent::__construct();
        $this->register(new \Silex\Provider\TwigServiceProvider(), ['twig.path' => __DIR__ . '/views']);
        $this->extend('twig', [$this, 'twigExtension']);
    }

    public function twigExtension(\Twig_Environment $twig)
    {
        $twig->addGlobal('foo', 'bar');
        return $twig;
    }
}

$myApp = new MySilex();
```

Throws an `\InvalidArgumentException` at the `extend` line, on the following check in `Container::extend`:

``` php
        if (!is_object($callable) || !method_exists($callable, '__invoke')) {
            throw new \InvalidArgumentException('Extension service definition is not a Closure or invokable object.');
        }
```

Shouldn't it be using [`is_callable`](http://php.net/manual/en/function.is-callable.php) instead here?

**Comment by ragboyjr** [comment]
I think that is more of a feature request than a bug. But it makes sense to me that Pimple should be checking for is callable instead.

**Comment by curry684** [comment]
I don't quite agree if the parameter is called and type hinted "callable" it would not be a bug not to accept the most basic of callables. I would have issued a PR right away to fix it but wanted to check first here what the intended behaviour is or was.

**Comment by ragboyjr** [comment]
Yes, looking at the source code, I see what you mean. `is_callable` would be the appropriate thing to do considering that it is type hinted as callable. If you make the PR, you should really update all of Pimple to support callables instead of just closures and objects that have the `__invoke` method.

**Comment by curry684** [comment]
Well when I tried to do that all hell rained down. The code down below makes some nasty assumptions about what can or cannot go in an SplObjectStorage.

For now I've limited the PR to just fixing this specific problem and not the services themselves.

**Comment by curry684** [comment]
Also found the likely reason this syntax was never supported - it's apparently 5.4 and above. Still shouldn't be disallowed of course, people just can't use it in 5.3.

**Comment by fabpot** [comment]
Closing this issue as Pimple is now closed for changes and will go into freeze mode.
