### ISSUE TITLE
Cannot override frozen service at WebTestCase

### ISSUE THREAD

**Issue by vicmosin** [silexphp/Pimple#203]
I use a `WebTestCase` in order to test controllers:
```
public function createApplication() {
     include __DIR__ . '../web/index_dev.php';

     $app['debug'] = true;
     $app['session.test'] = true;
     $app['helper'] = function ($app) {
            return new TestHelper($app);
     }; // fails!!

     return $app;
  }

  public function setUp() {
     parent::setUp();

     $this->client = parent::createClient();
 }
```

Silex 1.3 worked fine, but after upgrade to Silex 2.* I am facing the issue: `Cannot override frozen service "helper"`. I understand the meaning of error, but can't understand how can I fix it since in case of tests it is a valid behavior to override some implementations with mock/test ones.

**Comment by stof** [comment]
If it is already frozen at this point, it probably means that you have a place where you break the lazy-loading of services by getting the instance at a place where you are still expecting to be in the configuration phase of the container (thus freezing this service).

To debug it, search for any place accessing the ``helper`` service in your app (and if you don't find such a place, look for usages of services depending on ``helper``, and so on)

**Comment by vicmosin** [comment]
@stof Are definitions such `$app->before(..` or `$app->error(..` might be an issue? Or it is only about explicit access like `$app['helper']->method()` ?
