### ISSUE TITLE
Extending a service fails in test

### ISSUE THREAD

**Issue by vicmosin** [silexphp/Pimple#204]
```
public function createApplication() {
        include __DIR__ . '../web/index_dev.php';

        /** @var Application $app */
        $app['session.test'] = true;
        $app->extend('helper', function ($helper, $c) {
                return new TestHelper($c);
            }
        );

        return $app;
    }
```

fails with `Identifier "helper" does not contain an object definition.`.
P.S. `index_dev.php` contains an app and `$app['helper'] = function ($app) {return new Helper($app);};` definitions

**Comment by vicmosin** [comment]
The same issue I have with redefining mock session object via:
```
$app['session'] = new Session(new MockFileSessionStorage());
```

What is the correct way of redefining objects?

**Comment by ragboyjr** [comment]
http://pimple.sensiolabs.org/#modifying-services-after-definition

**Comment by vicmosin** [comment]
@ragboyjr Yes, I did it. And it fails with the error above

**Comment by ragboyjr** [comment]
Well, in your above example, you can only extend services that actually have been defined and that have been defined with a closure.

Here's a code example that shows your error:

```php
$container = new Pimple\Container();
$container['a'] = 'a';
$container->extend('a', function($a) { return $a . 'a'; }); 
```

You probably aren't setting the `helper` service correctly in a file or something.

**Comment by vicmosin** [comment]
@ragboyjr What exactly you mean by "aren't setting the `helper` correctly" ? I followed the docs, which says it's possible to define services as anonymous functions. So my definition is:
```
$app['helper'] = function ($app) {
    return new Helper($app);
};
```

**Comment by stof** [comment]
@vicmosin the fact that the helper service got frozen is probably related to *another* service being defined in a non-lazy way, and this other service depends on the helper.
So to debug it, look for places using the helper service in your project

**Comment by vicmosin** [comment]
@stof I understand that and I know where it's done. I just try to understand how can I modify service, following the docs. As far as I understand, http://pimple.sensiolabs.org/#modifying-services-after-definition should help me to solve frozen service issue

**Comment by stof** [comment]
@vicmosin if you extend all your services this way, you will indeed avoid freezing services early. Your issue is probably that you have 1 place not following this pattern to modify a service (and so it freezes some services earlier than wanted)

**Comment by vicmosin** [comment]
@stof please see that error that I have is different in case of modifying.. `Identifier "helper" does not contain an object definition.`

**Comment by HeahDude** [comment]
@vicmosin Do you actually boot or run the app in `index_dev.php`?

Maybe you should move the definitions in a bootstrap file returning the `$app` that you can require in both your front controller and in your test:
```php
// app/bootstrap.php
$app = new \Silex\Application();

$app['helper'] = ...

return $app;
```

```php
// web/index_dev.php
$app = require_once __DIR__.'/../app/bootstrap.php';
// ...

$app->run();
```

```php
// in your test
public function createApplication() {
    /** @var Application $app */
    $app = require_once __DIR__ . '/../app/bootstrap.php';

    $app['session.test'] = true;
    $app->extend('helper', function ($helper, $c) {
        return new TestHelper($c);
    });

    return $app;
}
```

**Comment by vicmosin** [comment]
@HeahDude Thanks man, you saved my day. The issue was in `$app->run()`!

**Comment by HeahDude** [comment]
@vicmosin Glad that helped, happy coding :)
