### ISSUE TITLE
Feature request: Support for tagging services?

### ISSUE THREAD

**Issue by samdjstevens** [silexphp/Pimple#205]
Hi, 

I was wondering if anyone would be interested in the implementation of tagging items in the container for grouped retrieval? i.e being able to tag a service as "middleware", and then being able to retrieve all container items (or all keys of the items?) that have been tagged as such.

I'd be happy to work on it myself, but not sure if it would be desired.

**Comment by GromNaN** [comment]
Hello,
Service tags are used by compiler passes. This is the kind of advanced feature I think Pimple is not willing to support; to stay it simple. Symfony Container is the way to go if you really need to tag your services.

Solution 1: Use a simple ArrayObject to store tags 
```php
$app['tags'] = new ArrayObject();

// Append services to a tag (process.steps could be SplPriorityQueue)
$app['tags']['process.steps'][] = 'my_step';
$app['my_step'] = function () { return new Step; };

// And use the tags when the service is initialized
$app['process'] = function ($app) {
    $p = new Process();
    foreach ($app['tags']['process.steps'] as $serviceName) {
        $p->add($app['serviceName']);
    }
    return $app;
};
```

Solution 2: Use service prefixes
```php
$app['process.steps.my_step'] = function () { return new Step; };

// And use the tags when the service is initialized
$app['process'] = function ($app) {
    $p = new Process();
    foreach ($app->keys() as $serviceName) {
        if (0 === strpos('process.steps.', $serviceName) {
            $p->add($app['serviceName']);
        }
    }
    return $app;
};
```

**Comment by samdjstevens** [comment]
Hi,

No worries, I thought that this probably would be a bit too out of scope for Pimple, I'll close the issue now.

And thanks for the suggestions on how to implement 👍
