### ISSUE TITLE
Events when resolving services

### ISSUE THREAD

**Issue by aambr** [silexphp/Pimple#207]
Hello,

Do you guys see potential in implementing observer pattern to the container so that it would be easy to extend services when fetched from it? Something like:

```php
$container = new Pimple;
$container->on('created', function($service) { return $service instanceof X ? $service->setX() : $service; }
```

**Comment by GromNaN** [comment]
What would you do with this event that you can't with the [`extend`](https://github.com/silexphp/Pimple/blob/master/src/Pimple/Container.php#L226) helper?

**Comment by aambr** [comment]
With `extend` you have to pass an ID of a service that you want to extend. I want to be able to alter services when for example one of them implement certain interface.

Like for example Symfony, injects container to every service that implements `ContainerAwareInterface`.

**Comment by jschreuder** [comment]
I don't know if you've ever looked into Pimple's code, but it's impressively simple. It consists of basicly just a few lines of code. This is what makes Pimple stand out: simplicity over a full feature-set. There's a ton of "nice small" features that could be added, but would also blow up its incredibly small codebase. Adding those would take away Pimple's defining feature of simplicity, if you need more than Pimple offers there's already a myriad of alternatives with bigger feature-sets.

**Comment by aambr** [comment]
I definitely agree that's one of the Pimple advantages, the simplicity. Although I often see high potencial for events which make things open to extend and closed for modifications with 
Although I often see high potencial for events which make things open to extend and closed for modifications with few lines of code.
I will search for something like that, hopefully something as nice as Pimple.

**Comment by fabpot** [comment]
I agree with the other commenters, this is out of the scope of a project like Pimple. Thanks for suggestion.
