### ISSUE TITLE
Recording and generating a trace of invoked services

### ISSUE THREAD

**Issue by alexweissman** [silexphp/Pimple#211]
It would be useful if Pimple could keep track of services as they are invoked, and expose a method for getting this list.

This would useful, for example, in debugging, to examine exactly which services were invoked (and in what order) for any given request (a non-trivial task in a large, complex application).  This would also be useful to a developer who is seeking to reduce the number of dependencies for a particular request.

**Comment by ragboyjr** [comment]
@alexweissman this kind of reminds me of #200. If there was a `ContainerInterface`, I think you could implement what you want with a Decorating container.

**Comment by fabpot** [comment]
Closing this issue as Pimple is now closed for changes and will go into freeze mode.
