### ISSUE TITLE
Handle dependencies of service providers

### ISSUE THREAD

**Issue by apapsch** [silexphp/Pimple#217]
I have some libraries which contain service providers:

- libfoo with FooService and FooServiceProvider
- libbar with BarService and BarServiceProvider

BarService depends on FooService. Therefore, BarServiceProvider uses the `foo` service from pimple:

```
function register(Container $c) {
    $c["bar"] = function ($c) {
        return new BarService($c["foo"]);
    };
}
```

Now, an application wants to use libbar and has no interest in libfoo. In order to use `bar` from the container, the app needs to register not only BarServiceProvider but also FooServiceProvider. This is inconvenient for applications, because they need to know the dependencies and they might change. It's also inconvenient for authors, because they first need to learn the dependencies, digging trough service providers.

In order to ease usage of services, there needs to be a way to let providers specify the providers it needs to have registered. I could imagine introducing a new interface `ServiceWithDependencyInterface` that providers can implement to return the providers it needs:

```
class Bar implements ServiceProviderInterface, ServiceWithDependencyInterface {
    public function register(Container $c) {...}
    public function getDependencies() {
        return [FooServiceProvider::class];
    }
}
```

Before a service providers `register` method is called, Pimple would fetch the dependencies and let them register recursively.

There's the issue of passing data to the service providers via the second argument to `Container::register`. Of course it's nice for dependency injection, but incompatible with `getDependencies`. So go full circle back to manually specifying all providers? I'd rather let `getDependencies` specify the dependencies with more detail:

```
class FooServiceProvider implements ServiceProviderInterface, ServiceWithDependencyInterface {
    public function register(Container $c) {...}
    public function getDependencies() {
        return [
            new DependencyOnServiceProvider(ConfigurationProvider::class),
            new DependencyOnParameter("foo.name")
        ];
    }
}
class BarServiceProvider implements ServiceProviderInterface, ServiceWithDependencyInterface {
    function getDependencies() {
        return [
            new DependencyOnServiceProvider(FooServiceProvider::class)
        ];
    }
}
interface DependencyInterface {

    /** @return boolean */
    public function dependencyFulfilled();

    public function resolveDependency();
}
class DependencyOnServiceProvider implements DependencyInterface{...}
class DependencyOnParameter implements DependencyInterface{...}
```

This allows different strategies to be applied for dependency resolution. Dependency classes might also accept a docstring parameter, specifying why the dependency is needed. If resolution fails, the docstring can be used in the exception message. With this approach, ease of usage is achieved and dependency injection preserved.

**Comment by apapsch** [comment]
I started working on this in a fork, will see how it goes.

**Comment by fabpot** [comment]
Closing this old ticket.
