### ISSUE TITLE
Freezing services bites with Silex sub requests and Doctrine flush exception

### ISSUE THREAD

**Issue by apapsch** [silexphp/Pimple#219]
This is a rather specific problem, but I believe the combination Silex (Pimple) + Doctrine for a REST API is common enough. If not Silex + Doctrine, then Symfony + Doctrine.

Anyway, I'm offering a batch endpoint in order to get related requests to the API executed in sequence. For this I use sub requests offered by Silex. Each sub request calls `EntityManager::flush` at some point. If an exception occurs in `flush`, Doctrine closes the entity manager and subsequent calls to `flush` produce exception "The EntityManager is closed".

To get out of this, it is required to recreate the entity manager from the closed one. The usual suggestion boils down to:

```
    if (!$manager->isOpen()) {
        $manager = $manager->create(
            $manager->getConnection(),
            $manager->getConfiguration()
        );
    }
```

But this approach doesn't suffice for the sub request case, where the entity manager is taken from the container. I tried overwriting the entity manager service in the container, but Pimple complains with "Cannot override frozen service". How might this be solved? As a quick solution, I disable the frozen checking, but I'd rather not in all cases.

As a side note: Doctrine docs suggest that `EntityManager::clear` might work, but it does not:

> Sometimes you want to clear the identity map of an EntityManager to start over. We use this regularly in our unit-tests to enforce loading objects from the database again instead of serving them from the identity map. You can call EntityManager#clear() to achieve this result.
http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/working-with-objects.html#entities-and-the-identity-map

It seems "reopening entity manager" is a more broad reset approach than "clearing identity map".

**Comment by ragboyjr** [comment]
@apapsch this is more of a doctrine/db issue rather than silex/pimple.

https://github.com/doctrine/doctrine2/issues/5933

**Comment by skalpa** [comment]
You can `unset` a service definition, that will allow you to redefine it.

```php
// Freezes the service
$em = $pimple['em'];
// Remove the service definition to prevent "Cannot override frozen service"
unset($pimple['em']);
// This will work
$pimple['em'] = function () {};
```

**Comment by apapsch** [comment]
So, freezing is merely there to make replacing more explicit? Otherwise I don't see much value for freezing in the first place, if you can just circumvent it.

**Comment by skalpa** [comment]
No, it's because you're not supposed to do that unless you clearly understand the consequences.

1. The service may have already been injected into another object.

```php
$pimple['dependent1'] = function ($pimple) {
    return FirstClass($pimple['em']);
};
$pimple['dependent2'] = function ($pimple) {
    return SecondClass($pimple['em']);
};
// This will inject the initial "em"
$service1 = $pimple['dependent1'];

// Later, we reset the definition
unset($pimple['em']);
$pimple['em'] = function () {};

// This will inject a new instance of the em service
// but won't change the instance that was injected into "dependent1"
$service2 = $pimple['dependent2'];
```

2. This may prevent the invocation of service extensions if not done correctly. Although, there's a way re-register the service exactly like it was before by doing this:

``php
$factory = $pimple->raw('em');
unset($pimple['em']);
$pimple['em'] = $factory;
```

Thus, freezing the service prevents mistakes as redefining an already loaded service is not something you'll want to do most of the times. As it's been said, here you're really facing a Doctrine problem and the only clean solution would be to fix it in Doctrine.

Now, if you don't inject the entity manager directly, resetting the service may work. Just be fully aware of what you're doing.

**Comment by apapsch** [comment]
Thanks for going into detail, I close this issue. In this case with sub requests I guess it's alright to replace the entity manager with `unset` because on error the sub request will finish and execution will proceed to next sub request. Therefore, entity manager in earlier sub requests is not of interest.
