### ISSUE TITLE
The error triggered when extending a frozen service is unfriendly/inconsistent

### ISSUE THREAD

**Issue by skalpa** [silexphp/Pimple#223]
This is the issue that gets fixed by the change I made to `extend()` in #222.

When attempting to `extend()` a frozen service, you may get two different exceptions:

### If the instantiated service is not invokable

This test will fail and throw an exception that doesn't really explain what went wrong:

```php
    if (!is_object($this->values[$id]) || !method_exists($this->values[$id], '__invoke')) {
        throw new \InvalidArgumentException(sprintf('Identifier "%s" does not contain an object definition.', $id));
    }
```

### If the instantiated service is invokable

The above test will not throw the exception, and the rest of `extend()` will be executed.

Finally, `$this[$id] = $extended` will fail with a `RuntimeException` when trying to change the definition of the frozen service.

**Comment by stof** [comment]
we should always forbid extending a frozen service with an early check instead

**Comment by skalpa** [comment]
@stof Yep, that's what [my fix does](https://github.com/silexphp/Pimple/blob/master/src/Pimple/Container.php#L237).

Am closing this one as #222 has been merged.
