### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by davejamesmiller** [silexphp/Pimple#227]
The Pimple website doesn't seem to be working at the moment...

With SSL (https://pimple.sensiolabs.org/ - which Google has indexed) I get an SSL error ("This server could not prove that it is pimple.sensiolabs.org; its security certificate is from *.eu.sensiosite.cloud.").

Without SSL (http://pimple.sensiolabs.org/) I get "Error 404. No route found for pimple.sensiolabs.org".

Not sure if this is a known issue / recent DNS change... :-)

**Comment by FinesseRus** [comment]
Both are working now
