### ISSUE TITLE
[Proposal] Deprecate the C extension

### ISSUE THREAD

**Issue by stof** [silexphp/Pimple#228]
The C extension is for PHP 5.x only.
Recent versions of Pimple have been optimized a lot in the userland implementation, which reduced the performance gap with the C extension. And PHP 7 did the rest of the work to improve performances.

thus, the C extension makes version management harder if you have multiple projects running on the same server (your project could magically get an older version of Pimple just because the server has an old version of the extension, and so you don't get the feature that you had while testing).

I suggest deprecating the C extension

**Comment by glensc** [comment]
care to post some benchmarks for comparison?

**Comment by stof** [comment]
Well, I don't have a PHP 5.x setup anymore to compile the extension, so I cannot do it for now.

But anyway, for PHP 7, the extension is not available (it would require reimplementing it from scratch).
And maintaining the extension creates more issue (see #222 where the new dependency on psr/container actually require re-implementing this dependency in C too for instance)

**Comment by fabpot** [comment]
Started it in #231 (@jpauli will add a deprecated notice when one uses the C ext)
