### ISSUE TITLE
Is pimple dead?

### ISSUE THREAD

**Issue by jnvsor** [silexphp/Pimple#243]
No commits in half a year and lots of talk about silex being dead. Is pimple?

I still prefer the pimple way of defining services, and I'd rather keep using it instead of symfony/laravel et. al.

**Comment by fabpot** [comment]
Pimple is not dead and still alive. The code is quite complete, so the fact that there is no activities here is rather normal. Pimple is independent from Silex and has its own life :)

**Comment by jnvsor** [comment]
@fabpot Thank you! This is great news :)
