### ISSUE TITLE
Service definition support for PSR-11 container

### ISSUE THREAD

**Issue by jeanCarloMachado** [silexphp/Pimple#248]
It would be nice to be able to receive in the service definition closure the PSR11 container instead of the pimple container when necessary. This has the benefit on enabling one to depend only on PSR11 instead of a specific implementation on it at the service definition side of things.

Maybe relying into the argument type hint.

```php
	'logger' => function (\Psr\Container\ContainerInterface $c) {
                $port = 666;
                 if ($c->has('logger.port')) {
                           $port = $c->get('logger.port');
                 }
      
		return new \Gyg\Gyg\Logger\Logger($c->get('logger.host'), $port);
	},
```

Do you agree this is useful? I can send a Pull Request if necessary.

**Comment by stof** [comment]
Relying on the typehint would force to use Reflection to examine the typehint of the closure, which would have a non-negligeable performance impact.

and given that Silex itself is marked as deprecated, I'm not sure what the plans for Pimple are.

**Comment by damijanc** [comment]
doing a simple test:  [https://3v4l.org/Dpa2E](https://3v4l.org/Dpa2E) shows that argument about performance penalty is pointless. But my test might be wrong or I am missing something.

**Comment by stof** [comment]
in this code snippet, you are **not** running code to examine what the typehint of the provided callable is. So you are **not** testing the performance impact of your proposal (you always pass the same argument to the callable)

**Comment by damijanc** [comment]
Why should I examine the type hint callable? It will fail if I pass the wrong type. What am I missing here?

**Comment by stof** [comment]
Well, *Pimple* is the one passing the right argument. And with your proposal, it would have to choose between the Pimple container (used currently) or the PSR-11 wrapper. We cannot just replace the argument with the PSR-11 wrapper as it would break all existing code.
So this means that Pimple would have to inspect the typehint of the argument to detect when it should pass the PSR-11 container (i.e. relying on the typehint, as you suggested).

**Comment by lennerd** [comment]
> and given that Silex itself is marked as deprecated, I'm not sure what the plans for Pimple are.

@stof Is there any more information about this?

**Comment by fabpot** [comment]
Closing this issue as Pimple is now closed for changes and will go into freeze mode.
