### ISSUE TITLE
Implement PSR-11

### ISSUE THREAD

**Issue by filips123** [silexphp/Pimple#249]
Implement [PSR-11 Container Interface](https://www.php-fig.org/psr/psr-11/) (which is now accepted) in [Pimple Container](https://github.com/silexphp/Pimple/blob/master/src/Pimple/Container.php).

**Comment by filips123** [comment]
The PR #233 is already added.

**Comment by lyrixx** [comment]
@filips123 I'm not sure to understand your issue. Pimple already implement this PSR ...

**Comment by filips123** [comment]
I opened this issue before I saw that there is support for PSR-11. I only mean to implement it without helper class but I now see that you can't do that due some reasons.
