### ISSUE TITLE
Bump of minimal php version to 7.2.5, breaks backward compatibility

### ISSUE THREAD

**Issue by GDmac** [silexphp/Pimple#257]
(as mentioned on commit 65c694be65247a5621460da8f50b28e996b5763b)

The bump of minimal php version to 7.2.5 for pimple 3.3.0 comes a bit as a surprise. 
There is no code requiring this change, it is only a change in composer.json
from ``php: >=5.3.0`` into ``php: ^7.2.5``

This breaks installs on services (that are a bit behind with php) for no particular requirement.
Since december 2018 we have require { pimple/pimple : ^3.0 } which used to work,
and now gives: Problem ... pimple/pimple v3.3.0 requires php ^7.2.5

**Comment by stof** [comment]
This does not break anything if you don't use `--ignore-platform-reqs` when running Composer, as Composer takes the PHP version into account.

**Comment by glensc** [comment]
Also, if you create `composer.lock` with different PHP version than production PHP, then you should at least override `platform.version` in your `composer.json` to ensure dependencies are resolved aginst your target PHP version:
- https://github.com/eventum/eventum/blob/v3.8.9/composer.json#L127

@stof is there a composer section for all of this? could just point people there for this very common problem :)

**Comment by glensc** [comment]
And, perhaps your initial problem is that you have a project and don't track `composer.lock`

There's a common misconception about whether the lock needs to be committed to the repository or not.

It can be summarized with two opposite scenarios:
- projects: keep the lock in projects where it really matters (production is deployed from it): https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control
- libraries: do not keep lock for libraries: https://getcomposer.org/doc/02-libraries.md#lock-file

**Comment by glensc** [comment]
Also, @GDmac, consider updating issue title to be something meaningful (currently it is titled as `Mini`)

**Comment by GDmac** [comment]
the **backward compatibility breaking** requirement for php >= 7.2.5 
should be in a separate **major version** of pimple (4.0.x)

currently ``require { pimple/pimple : ~3.2 }`` or ``require { pimple/pimple : ~3 }``
breaks a working install on composer update.

At the very least it should have been in a separate minor version (3.4.0)
so we could have resorted to having the latest commits between 3.2 and 3.3 
and on our side a composer requirement change of ``pimple/pimple: <=3.3``

**Comment by fabpot** [comment]
I think things have been well explained now.

**Comment by GDmac** [comment]
can you then at least backport the changes between 3.2.3 and 3.3.0 into 3.2.4 please?

**Comment by fabpot** [comment]
The changes are purely cosmetic, no bug fixes. The reason why I dropped old versions is also because Travis don't have them anymore (or at least testing them is more complex). In any case, Pimple is done now. I don't envision any more changes. i think it's time to declare it done and closed for new features.
